export enum Size {
	XXXXS = 'var(--size-xxxxs)',
	XXXS = 'var(--size-xxxs)',
	XXS = 'var(--size-xxs)',
	XS = 'var(--size-xs)',
	S = 'var(--size-s)',
	M = 'var(--size-m)',
	L = 'var(--size-l)',
	XL = 'var(--size-xl)',
	XXL = 'var(--size-xxl)',
	XXXL = 'var(--size-xxxl)',
	XXXXL = 'var(--size-xxxxl)',
	XXXXXL = 'var(--size-xxxxxl)',
	Special6 = 'var(--size-special6)',
}
