name: Deploy
on:
  push:
    branches: main
jobs:
  build-and-deploy:
    name: Build and deploy site
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: production
      cancel-in-progress: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Project Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
          AIRTABLE_BASE: ${{ secrets.AIRTABLE_BASE }}
          NEXT_PUBLIC_MAPKIT_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPKIT_TOKEN }}
          NEXT_PUBLIC_SITESNOTICE_ADDRESS: ${{ vars.NEXT_PUBLIC_SITESNOTICE_ADDRESS }}
          NEXT_PUBLIC_SITESNOTICE_EMAIL: ${{ vars.NEXT_PUBLIC_SITESNOTICE_EMAIL }}
          NEXT_PUBLIC_SITESNOTICE_PHONE: ${{ vars.NEXT_PUBLIC_SITESNOTICE_PHONE }}

      - name: Verify build
        run: ls -la out

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.sftp_server }}
          username: ${{ secrets.sftp_username }}
          password: ${{ secrets.sftp_password }}
          protocol: ftps
          local-dir: ./out/
